// ===== AI Replacement Map — methodology + ~90 occupations =====
//
// Methodology: each occupation is hand-scored on four axes (0–100):
//   rcog · routine cognitive       (text drafting, summarising, structured retrieval)
//   rphy · routine physical        (assembly, sorting, repetitive motion)
//   nrcog · non-routine cognitive  (judgment, novel synthesis, ambiguity)
//   nrint · non-routine interpersonal (presence, empathy, dexterity in unstructured settings)
//
// Composite exposure (0–100) is given directly per row, calibrated against the four sub-scores.
// Higher = more exposed to AI substitution / amplification within ~5 years.
// Lower = AI may augment, but core role stays human.
//
// All scores are one analyst's structural read, not a forecast. Honest disclaimers throughout.

window.SECTORS = {
  knowledge: { en: "Knowledge work",   zh: "知识工作" },
  creative:  { en: "Creative",         zh: "创意" },
  health:    { en: "Healthcare & care", zh: "医疗与照护" },
  education: { en: "Education",        zh: "教育" },
  trades:    { en: "Trades",           zh: "技工" },
  manuf:     { en: "Manufacturing",    zh: "制造" },
  transport: { en: "Transport",        zh: "运输" },
  hospitality:{en: "Hospitality & service", zh: "服务业" },
  security:  { en: "Security & defence", zh: "安全与国防" },
  finance:   { en: "Finance",          zh: "金融" },
  legal:     { en: "Legal",            zh: "法律" },
  science:   { en: "Science & research", zh: "科研" },
  public:    { en: "Public service",   zh: "公共服务" },
};

// composite, [rcog, rphy, nrcog, nrint], en_note, zh_note
window.JOBS = [
  // ===== Knowledge work =====
  { id:"data-entry", en:"Data entry clerk", zh:"数据录入员", sector:"knowledge", composite:96,
    sub:[95,30,15,10],
    en_note:"Pure routine cognitive throughput. Already mostly automated by OCR + LLM extraction; the residual job is exception-handling.",
    zh_note:"纯粹的常规认知吞吐。OCR 加 LLM 提取已基本自动化；残留工作是异常处理。"},
  { id:"telemarketer", en:"Telemarketer", zh:"电话销售员", sector:"knowledge", composite:94,
    sub:[80,15,20,40],
    en_note:"Scripted dialogue, scripted objection-handling. AI voice agents already match human conversion at the low end.",
    zh_note:"脚本化对话、脚本化反驳处理。低端市场上，AI 语音代理已与人工转化率持平。"},
  { id:"customer-service", en:"Customer service rep", zh:"客服代表", sector:"knowledge", composite:90,
    sub:[80,10,35,55],
    en_note:"Routine inquiries are fully automatable; complex emotional escalations remain human, but those are 10% of volume.",
    zh_note:"常规咨询已全自动化；复杂的情绪升级仍需人工，但仅占总量约 10%。"},
  { id:"bookkeeper", en:"Bookkeeper", zh:"记账员", sector:"knowledge", composite:88,
    sub:[90,5,40,15],
    en_note:"Standardised accounting workflows are the textbook AI use case. Senior accountants survive; bookkeepers do not.",
    zh_note:"标准化会计流程正是 AI 的范式用例。资深会计师存活，记账员不会。"},
  { id:"copywriter-junior", en:"Copywriter (entry-level)", zh:"文案（初级）", sector:"knowledge", composite:85,
    sub:[80,5,55,30],
    en_note:"Generic marketing copy and SEO blurbs are the LLM's home turf. Senior brand voice and cultural craft are not.",
    zh_note:"泛用营销文案与 SEO 短文是 LLM 的主场。资深品牌之声与文化匠艺不是。"},
  { id:"translator", en:"Translator (general business)", zh:"翻译（一般商务）", sector:"knowledge", composite:82,
    sub:[75,5,55,40],
    en_note:"Functional translation has been a solved problem for years. Literary, legal certified, and culturally-loaded translation persist.",
    zh_note:"功能性翻译多年来已属已解问题。文学、法定认证、文化负载型翻译仍保留。"},
  { id:"paralegal", en:"Paralegal", zh:"律师助理", sector:"knowledge", composite:80,
    sub:[80,5,50,40],
    en_note:"Document review, citation pulling, deposition summarisation — exactly the workflow LLMs accelerate 5–20×.",
    zh_note:"文档审阅、引文抽取、笔录摘要——恰是 LLM 可加速 5—20 倍的工作流。"},
  { id:"market-research", en:"Market research analyst", zh:"市场研究分析师", sector:"knowledge", composite:75,
    sub:[70,5,65,40],
    en_note:"Survey analysis and trend write-ups compress dramatically. The senior layer that frames the question survives.",
    zh_note:"问卷分析与趋势报告大幅压缩。提出问题的资深层留存。"},
  { id:"hr-specialist", en:"HR specialist (operations)", zh:"人力资源专员", sector:"knowledge", composite:72,
    sub:[70,10,55,50],
    en_note:"Resume screening, scheduling, policy-FAQ — automated. Conflict resolution and culture-building are human-bound.",
    zh_note:"简历筛选、排期、政策 FAQ——已被自动化。冲突调解与文化建设受人之约束。"},
  { id:"recruiter-mass", en:"Recruiter (high-volume)", zh:"招聘（大规模）", sector:"knowledge", composite:78,
    sub:[75,10,50,55],
    en_note:"Sourcing pipelines and initial screens collapse to AI. Executive search persists because trust is the deliverable.",
    zh_note:"人选搜寻与初筛已坍缩至 AI。猎头层因'信任即交付物'而留存。"},
  { id:"recruiter-exec", en:"Recruiter (executive)", zh:"猎头（高管）", sector:"knowledge", composite:38,
    sub:[35,5,75,75],
    en_note:"Closing a CEO depends on a years-long network of warm trust. AI can prep the briefing, not place the call.",
    zh_note:"敲定 CEO 依赖经年累月的温信任网络。AI 可备简报，不能拨通那通电话。"},
  { id:"junior-analyst", en:"Junior financial analyst", zh:"初级金融分析师", sector:"finance", composite:75,
    sub:[80,5,60,30],
    en_note:"Excel modelling and earnings-call summarisation — already the top demoed AI use case in finance.",
    zh_note:"Excel 建模与电话会摘要——已是金融业 AI 头号示范用例。"},
  { id:"senior-analyst", en:"Senior portfolio analyst", zh:"资深组合分析师", sector:"finance", composite:42,
    sub:[40,5,80,55],
    en_note:"Quantitative analysis is augmented; client-facing judgment under uncertainty remains a moat.",
    zh_note:"定量分析得以增强；面向客户、不确定性下的判断仍是护城河。"},
  { id:"product-manager", en:"Product manager", zh:"产品经理", sector:"knowledge", composite:48,
    sub:[45,5,80,60],
    en_note:"Spec drafting and ticket triage are AI-assisted. Prioritisation, stakeholder alignment, and 'what to build' are not.",
    zh_note:"需求文档与工单分诊已由 AI 协助。优先级、利益相关者协调、'造什么'仍非 AI 所能。"},
  { id:"junior-swe", en:"Software engineer (junior)", zh:"软件工程师（初级）", sector:"knowledge", composite:62,
    sub:[60,5,70,30],
    en_note:"AI pair-programming amplifies output 2–4×, but also raises the floor employers expect. The junior rung is shrinking.",
    zh_note:"AI 结对编程使产出增 2—4 倍，雇主底线随之抬升。初级阶梯正在收窄。"},
  { id:"senior-swe", en:"Software engineer (senior)", zh:"软件工程师（资深）", sector:"knowledge", composite:35,
    sub:[35,5,85,55],
    en_note:"System design, debugging novel failure modes, and judgment over architecture are augmented, not replaced.",
    zh_note:"系统设计、新颖失效调试、架构判断——被增强，未被替代。"},
  { id:"data-scientist", en:"Data scientist", zh:"数据科学家", sector:"knowledge", composite:50,
    sub:[55,5,75,45],
    en_note:"Routine analysis and notebook generation are AI-tier. Defining the right metric and the right experiment is not.",
    zh_note:"常规分析与 notebook 生成已属 AI 级别。定义正确指标与实验则不是。"},
  { id:"ux-designer", en:"UX designer", zh:"UX 设计师", sector:"creative", composite:55,
    sub:[50,5,70,55],
    en_note:"Mockups, design systems, copy ideation accelerate hugely; user-research synthesis and taste judgment do not.",
    zh_note:"线框、设计系统、文案构思大幅加速；用户研究综合与品味判断不会。"},
  { id:"sm-manager", en:"Social media manager", zh:"社媒运营", sector:"knowledge", composite:70,
    sub:[70,5,50,55],
    en_note:"Content scheduling and post-drafting are largely automatable. The community-management layer is what survives.",
    zh_note:"内容排期与发文起草大半可自动化。留存者是社区运营层。"},
  { id:"editor-book", en:"Editor (book)", zh:"图书编辑", sector:"creative", composite:42,
    sub:[40,5,75,55],
    en_note:"Copy-editing accelerates; structural editing and acquisitions taste are still bound to a curator's judgment.",
    zh_note:"文字校对得以加速；结构编辑与选题品味仍系于编辑判断。"},
  { id:"investigative-journo", en:"Investigative journalist", zh:"调查记者", sector:"knowledge", composite:25,
    sub:[20,5,80,80],
    en_note:"Records-pulling is augmented; sources, on-the-ground reporting, and cross-jurisdictional persistence are deeply human.",
    zh_note:"档案抽取得以增强；线人、现场报道、跨辖区坚持，皆深植于人。"},
  { id:"beat-reporter", en:"Beat reporter (general)", zh:"线口记者（一般）", sector:"knowledge", composite:62,
    sub:[60,5,55,55],
    en_note:"Routine wire-style write-ups are increasingly AI-drafted. Original reporting and judgment differentiate.",
    zh_note:"常规通稿越来越由 AI 起草。原创采访与判断方为区分点。"},
  { id:"insurance-uw", en:"Insurance underwriter", zh:"保险核保员", sector:"finance", composite:80,
    sub:[85,5,45,20],
    en_note:"Decision rules + document parsing — automation hit this category early and continues.",
    zh_note:"决策规则 + 文档解析——自动化对此类工作早已落地，并持续推进。"},
  { id:"claims-adjuster-auto", en:"Insurance claims adjuster (auto)", zh:"理赔（车险）", sector:"finance", composite:88,
    sub:[80,15,40,30],
    en_note:"Photo-based claims with rule-following are the canonical computer-vision deployment.",
    zh_note:"基于照片、按规则处理的理赔，是计算机视觉的范式部署。"},
  { id:"compliance-officer", en:"Compliance officer", zh:"合规官", sector:"finance", composite:55,
    sub:[60,5,65,40],
    en_note:"Document review and rule-mapping accelerate; final-call accountability stays with a regulated human.",
    zh_note:"文档审查与规则映射得以加速；最终问责仍归于受监管的人。"},
  { id:"financial-advisor", en:"Financial advisor (retail)", zh:"理财顾问（零售）", sector:"finance", composite:48,
    sub:[45,5,60,70],
    en_note:"Robo-advisors handle the model portfolios; the relationship and behavioural-coaching layer is what's billed.",
    zh_note:"机器人投顾处理模型组合；关系与行为辅导层是真正可计费之物。"},
  { id:"bank-teller", en:"Bank teller", zh:"银行柜员", sector:"finance", composite:78,
    sub:[70,30,30,40],
    en_note:"Basic transactions migrated to apps and ATMs years ago. Branch tellers persist mostly for trust signalling.",
    zh_note:"基础交易多年前已迁至 app 与 ATM。柜员留存多为信任信号。"},
  { id:"tax-prep", en:"Tax preparer", zh:"税务申报员", sector:"finance", composite:80,
    sub:[85,5,40,25],
    en_note:"Standard returns are software's home turf. Specialised tax counsel for high-net-worth or business audits remains.",
    zh_note:"标准报税是软件主场。高净值或企业审计的专业税务顾问留存。"},

  // ===== Legal =====
  { id:"contract-lawyer", en:"Contract review lawyer", zh:"合同审查律师", sector:"legal", composite:85,
    sub:[85,5,55,30],
    en_note:"Mark-up and clause-comparison workflows are exactly what LLMs do. Negotiation persists; review collapses.",
    zh_note:"批注与条款对比工作流正是 LLM 所擅。谈判留存；审查坍缩。"},
  { id:"litigator", en:"Litigation lawyer", zh:"诉讼律师", sector:"legal", composite:35,
    sub:[35,5,80,70],
    en_note:"Discovery is augmented massively; the courtroom and the deposition table are not. Strategic judgment is the moat.",
    zh_note:"证据开示得到极大增强；法庭与笔录现场未被替代。战略判断是护城河。"},
  { id:"judge", en:"Judge", zh:"法官", sector:"legal", composite:15,
    sub:[15,2,80,80],
    en_note:"Public legitimacy of judicial decision-making is, structurally, an exclusively human institution. AI is a research tool.",
    zh_note:"司法决策的公共合法性，在结构上专属人类制度。AI 是研究工具。"},
  { id:"patent-examiner", en:"Patent examiner", zh:"专利审查员", sector:"legal", composite:60,
    sub:[65,5,65,30],
    en_note:"Prior-art search dramatically accelerates; inventiveness judgment remains a human regulatory call.",
    zh_note:"现有技术检索极大加速；创造性判断仍属人工监管裁量。"},

  // ===== Healthcare =====
  { id:"radiologist", en:"Radiologist", zh:"放射科医生", sector:"health", composite:55,
    sub:[55,5,75,40],
    en_note:"Image classification has matched senior humans on narrow tasks since 2019; clinical interpretation and litigation accountability persist.",
    zh_note:"自 2019 年起图像分类在窄任务上已比肩资深人工；临床解读与诉讼问责留存。"},
  { id:"pathologist", en:"Pathologist", zh:"病理科医生", sector:"health", composite:50,
    sub:[55,5,75,40],
    en_note:"Slide review is augmented; diagnostic sign-out remains an MD-credentialed act.",
    zh_note:"切片审阅得到增强；签发诊断仍是医师资格行为。"},
  { id:"surgeon", en:"Surgeon", zh:"外科医生", sector:"health", composite:12,
    sub:[10,15,80,80],
    en_note:"Robotic surgery is a power-tool, not a replacement. The judgment, the dexterity, and the legal accountability are human.",
    zh_note:"机器人外科是动力工具，非替代。判断、操作灵巧、法律问责，皆属人。"},
  { id:"gp", en:"General practitioner", zh:"全科医生", sector:"health", composite:32,
    sub:[35,5,75,75],
    en_note:"Triage and routine prescription accelerate; the diagnostic ambiguity at the consultation door is the human-bound part.",
    zh_note:"分诊与常规处方加速；门诊的诊断不确定性属人之核心。"},
  { id:"psychiatrist", en:"Psychiatrist", zh:"精神科医生", sector:"health", composite:18,
    sub:[15,5,75,90],
    en_note:"Therapeutic alliance is the treatment in many cases. AI can take notes; it cannot be the doctor.",
    zh_note:"许多案例中治疗联盟即治疗本身。AI 可记笔记，不能为医师。"},
  { id:"therapist", en:"Therapist / counsellor", zh:"心理治疗师 / 咨询师", sector:"health", composite:22,
    sub:[18,5,70,90],
    en_note:"AI chat companions exist and grow; clinical work for serious presentations is and will remain bound to a regulated human.",
    zh_note:"AI 陪伴聊天存在且增长；严重表征下的临床工作仍属受监管之人。"},
  { id:"nurse-rn", en:"Registered nurse", zh:"注册护士", sector:"health", composite:14,
    sub:[15,30,55,90],
    en_note:"Documentation accelerates dramatically; bedside care, clinical observation, and patient advocacy are deeply human.",
    zh_note:"病历加速极大；床旁护理、临床观察、病患代言深植于人。"},
  { id:"nurse-aide", en:"Nursing assistant", zh:"护理员", sector:"health", composite:10,
    sub:[5,40,30,90],
    en_note:"The most exposure-resistant job class in this entire dataset — bound to embodied unstructured care.",
    zh_note:"全数据集中最抗替代的工种——绑定于具身的非结构化照护。"},
  { id:"pharmacist", en:"Pharmacist", zh:"药剂师", sector:"health", composite:48,
    sub:[55,15,55,55],
    en_note:"Dispensing is partly automated; medication counselling and clinical interaction remain credentialed acts.",
    zh_note:"配药已部分自动化；用药咨询与临床互动仍是凭证性行为。"},
  { id:"vet", en:"Veterinarian", zh:"兽医", sector:"health", composite:18,
    sub:[20,15,70,80],
    en_note:"Animal handling, complex differential diagnosis, surgery — all bound to the embodied veterinarian.",
    zh_note:"动物操控、复杂鉴别诊断、手术——皆绑定于具身兽医。"},
  { id:"physio", en:"Physical therapist", zh:"物理治疗师", sector:"health", composite:14,
    sub:[10,30,55,90],
    en_note:"Touch-based rehabilitation is the canonical AI-resistant activity.",
    zh_note:"基于触感的康复，是抗 AI 替代的范式工作。"},
  { id:"childcare", en:"Childcare worker", zh:"幼儿保育员", sector:"health", composite:8,
    sub:[5,20,30,95],
    en_note:"Care of pre-verbal humans by definition cannot be subcontracted to a non-human agent.",
    zh_note:"对前语言期人类的照护，按定义无法转包给非人代理。"},

  // ===== Education =====
  { id:"k12-teacher", en:"K-12 teacher", zh:"中小学教师", sector:"education", composite:25,
    sub:[20,10,55,90],
    en_note:"Lesson planning and grading accelerate; classroom presence with 30 children is an irreducibly human act.",
    zh_note:"备课与批改加速；与三十名儿童共处教室之事，是不可化约之人之行。"},
  { id:"professor-research", en:"Research professor", zh:"研究型教授", sector:"education", composite:38,
    sub:[35,5,80,55],
    en_note:"Lit review and admin compress hugely; mentorship, originality, and grant judgment remain.",
    zh_note:"文献综述与行政大幅压缩；指导、原创性、申请书判断仍存。"},
  { id:"tutor-1on1", en:"Tutor (1-on-1)", zh:"一对一辅导员", sector:"education", composite:55,
    sub:[40,5,55,75],
    en_note:"AI tutors are improving fast; the floor of competence is rising and threatens the lower-credential tutoring market.",
    zh_note:"AI 辅导器进步迅速；能力下限抬升，威胁低凭证辅导市场。"},
  { id:"curriculum-designer", en:"Curriculum designer", zh:"课程设计师", sector:"education", composite:58,
    sub:[55,5,65,40],
    en_note:"Lesson generation and content scaffolding accelerate dramatically; pedagogical judgment is what's left.",
    zh_note:"课程生成与内容支架加速极大；教学法判断是剩下之物。"},
  { id:"essay-grader", en:"Standardised-test essay grader", zh:"标准化考试作文评卷员", sector:"education", composite:92,
    sub:[90,5,50,15],
    en_note:"Rubric-based scoring is the AI base case. Already partially deployed in many testing systems.",
    zh_note:"基于评分量表的打分是 AI 基础情形。在多个考试系统中已部分部署。"},

  // ===== Trades (mostly low exposure) =====
  { id:"plumber", en:"Plumber", zh:"水管工", sector:"trades", composite:8,
    sub:[5,40,40,80],
    en_note:"Diagnosis in unfamiliar physical environments + dexterity in tight spaces. Robotics is decades behind.",
    zh_note:"于陌生物理环境中诊断 + 狭小空间内的灵巧操作。机器人落后数十年。"},
  { id:"electrician", en:"Electrician", zh:"电工", sector:"trades", composite:10,
    sub:[10,40,50,75],
    en_note:"Code knowledge is augmented; pulling wire through old walls is not.",
    zh_note:"规范知识得以增强；在旧墙中穿线则不会。"},
  { id:"carpenter", en:"Carpenter", zh:"木工", sector:"trades", composite:8,
    sub:[5,40,40,80],
    en_note:"Bespoke joinery, framing, fitting — embodied craft.",
    zh_note:"定制榫卯、框架、装配——具身匠艺。"},
  { id:"hvac", en:"HVAC technician", zh:"暖通技师", sector:"trades", composite:12,
    sub:[10,35,50,75],
    en_note:"Diagnostic AI helps; rooftop access, ductwork, and refrigerant handling do not change.",
    zh_note:"诊断 AI 有助益；屋顶作业、风管、制冷剂处理不会改变。"},
  { id:"welder", en:"Welder", zh:"焊工", sector:"trades", composite:18,
    sub:[15,45,40,55],
    en_note:"Robot-welding is mature for repeated geometries; field welding on irregular structures is human.",
    zh_note:"重复几何的机器人焊接已成熟；现场不规则结构的焊接仍属人。"},
  { id:"auto-mech", en:"Auto mechanic", zh:"汽车修理工", sector:"trades", composite:22,
    sub:[20,40,55,55],
    en_note:"Diagnostics is AI-assisted; the wrench at the engine bay is not. EV transition is the bigger threat.",
    zh_note:"诊断由 AI 协助；引擎舱里的扳手不是。电动转型是更大威胁。"},

  // ===== Manufacturing =====
  { id:"line-electronics", en:"Assembly line worker (electronics)", zh:"电子装配工", sector:"manuf", composite:78,
    sub:[40,75,25,30],
    en_note:"Robots already dominate where consistent geometry exists; remaining humans handle edge cases and reconfiguration.",
    zh_note:"几何一致处机器人已主导；残留人工处理边缘情况与重组。"},
  { id:"line-auto", en:"Assembly line worker (auto)", zh:"汽车装配工", sector:"manuf", composite:70,
    sub:[35,70,30,30],
    en_note:"The original automation case. Most physical assembly was robotised in the 1990s; final-fit and quality remain.",
    zh_note:"自动化最初案例。多数物理装配于 1990 年代机器人化；最终装配与质检留存。"},
  { id:"qc-inspector", en:"Quality control inspector", zh:"质量检验员", sector:"manuf", composite:75,
    sub:[70,30,45,20],
    en_note:"Computer vision is mature for most defect classes. Final adjudication stays with a credentialed human.",
    zh_note:"对多数缺陷类别，计算机视觉已成熟。最终判定仍归有资质之人。"},
  { id:"cnc-machinist", en:"CNC machinist", zh:"数控机床操作员", sector:"manuf", composite:55,
    sub:[55,40,55,30],
    en_note:"Programming is increasingly AI-assisted; setup, fixturing, and small-batch artistry remain.",
    zh_note:"编程越来越由 AI 协助；装夹、夹具、小批量工艺仍存。"},
  { id:"industrial-designer", en:"Industrial designer", zh:"工业设计师", sector:"creative", composite:48,
    sub:[40,5,75,50],
    en_note:"Generative-design tools accelerate ideation; manufacturing-feasibility judgment and brand language are not yet AI's domain.",
    zh_note:"生成式设计工具加速构思；制造可行性判断与品牌语言尚非 AI 域。"},

  // ===== Transport =====
  { id:"truck-longhaul", en:"Long-haul truck driver", zh:"长途货车司机", sector:"transport", composite:55,
    sub:[20,55,40,40],
    en_note:"Highway autonomy works on closed corridors today; full unrestricted deployment is years out, not decades.",
    zh_note:"高速公路自动驾驶今日已在封闭走廊上运行；完全无限制部署以年计，非以十年计。"},
  { id:"taxi", en:"Taxi / rideshare driver", zh:"出租 / 网约车司机", sector:"transport", composite:60,
    sub:[20,55,45,50],
    en_note:"Robotaxis are operating in several US cities. Geographic and regulatory roll-out is the bottleneck, not the tech.",
    zh_note:"无人出租已在美国数城市运营。地理与监管推开是瓶颈，非技术。"},
  { id:"pilot-commercial", en:"Commercial pilot", zh:"商用飞行员", sector:"transport", composite:18,
    sub:[15,5,75,70],
    en_note:"Autopilots fly straight-and-level; regulators, unions, and tail-risk events ensure two humans up front for at least the next decade.",
    zh_note:"自动驾驶维持平飞；监管、工会、尾部风险事件，将至少在下一十年保留两名人在前。"},
  { id:"delivery-lastmile", en:"Delivery driver (last-mile)", zh:"末端配送员", sector:"transport", composite:48,
    sub:[20,50,35,55],
    en_note:"Drones and sidewalk robots take the easiest cases; flights of stairs and apartment doors keep humans in the loop.",
    zh_note:"无人机与街面机器人接管最简单案例；楼梯与公寓门将人留在环内。"},
  { id:"bus-driver", en:"Bus driver", zh:"公交车司机", sector:"transport", composite:38,
    sub:[15,40,35,60],
    en_note:"Dedicated lanes admit autonomy faster; mixed-traffic urban routes are still human-driven for trust and judgment reasons.",
    zh_note:"专用车道更快引入自动驾驶；混行城市线路因信任与判断仍由人驾驶。"},
  { id:"train-operator", en:"Train operator", zh:"列车司机", sector:"transport", composite:55,
    sub:[40,30,40,45],
    en_note:"Driverless metros exist; long-distance and freight rail are slower to convert because of legacy signalling and dispute resolution.",
    zh_note:"无人地铁已存在；长途与货运铁路因传统信号与争议处理而转换较慢。"},

  // ===== Hospitality =====
  { id:"waiter", en:"Waiter / server", zh:"服务员", sector:"hospitality", composite:25,
    sub:[15,40,35,75],
    en_note:"Tablets take orders; carrying plates, reading rooms, and recovering from errors keep humans on the floor.",
    zh_note:"平板下单；端盘、读懂氛围、纠错，将人留在场上。"},
  { id:"cook", en:"Line cook", zh:"厨房厨工", sector:"hospitality", composite:18,
    sub:[10,40,35,70],
    en_note:"Some chains have automated narrow-menu fryers and grills; broad menu execution is far from solved.",
    zh_note:"部分连锁已自动化窄菜单的炸炉与铁板；宽菜单执行远未解决。"},
  { id:"chef-head", en:"Head chef", zh:"主厨", sector:"hospitality", composite:20,
    sub:[15,15,75,75],
    en_note:"Recipe development, palate, kitchen leadership, customer dining experience — all human-bound.",
    zh_note:"配方研发、味觉、后厨领导、宾客用餐体验——皆系于人。"},
  { id:"bartender", en:"Bartender", zh:"调酒师", sector:"hospitality", composite:22,
    sub:[20,30,30,80],
    en_note:"Robotic bars exist as novelties; the bar's job is presence and hospitality, not pour accuracy.",
    zh_note:"机器人酒吧作为噱头存在；酒吧的工作是临在与待客，非倒酒精度。"},
  { id:"hotel-receptionist", en:"Hotel receptionist", zh:"酒店前台", sector:"hospitality", composite:60,
    sub:[60,5,35,55],
    en_note:"Self check-in kiosks plus chat handle volume; the human stays for high-touch, complaint, and complex booking situations.",
    zh_note:"自助入住机加聊天机器人处理量；人留作高触感、投诉、复杂预订场景。"},
  { id:"housekeeper", en:"Housekeeper", zh:"客房清洁工", sector:"hospitality", composite:15,
    sub:[10,55,25,70],
    en_note:"Cleaning robotics is brittle on cluttered, varied real-world rooms. Humans persist.",
    zh_note:"于杂乱多变的现实房间中，清洁机器人脆弱。人留存。"},
  { id:"travel-agent", en:"Travel agent (general)", zh:"旅行顾问（一般）", sector:"hospitality", composite:88,
    sub:[80,5,40,55],
    en_note:"Booking sites collapsed this category once already; LLM travel planners finish the job.",
    zh_note:"订票网站已使该类别坍缩一次；LLM 旅行规划完成余下工作。"},
  { id:"tour-guide", en:"Tour guide", zh:"导游", sector:"hospitality", composite:32,
    sub:[25,10,55,80],
    en_note:"Audio-guides have existed for decades; live guides survive on charisma, local relationships, and improvisation.",
    zh_note:"语音导览存在已数十年；真人导游凭魅力、当地关系、即兴而存。"},

  // ===== Security & defence =====
  { id:"security-guard", en:"Security guard", zh:"保安", sector:"security", composite:30,
    sub:[20,30,35,70],
    en_note:"CCTV + analytics replaces some posts; presence as deterrent and judgement-on-the-spot keeps humans staffed.",
    zh_note:"闭路电视加分析替代部分岗位；威慑性的临在与现场判断使人保有岗位。"},
  { id:"police", en:"Police officer", zh:"警察", sector:"security", composite:18,
    sub:[15,15,55,85],
    en_note:"Records work and analysis is augmented; patrol, arrest, and use-of-force decisions are bound to a sworn officer.",
    zh_note:"档案工作与分析得以增强；巡逻、逮捕、使用武力的决策，绑定于宣誓警员。"},
  { id:"soldier", en:"Soldier (combat arms)", zh:"作战士兵", sector:"security", composite:25,
    sub:[10,25,55,75],
    en_note:"Drones and autonomy reshape the doctrine; humans remain for the kill-chain accountability and the unpredictable terrain.",
    zh_note:"无人机与自动化重塑战术；人留作打击链问责与不可预测地形。"},
  { id:"drone-operator", en:"Drone operator (military)", zh:"军用无人机操作员", sector:"security", composite:55,
    sub:[40,15,55,40],
    en_note:"As autonomy grows, the operator's job concentrates on legal authorization and target judgment — fewer operators for more sorties.",
    zh_note:"随自动化扩展，操作员的工作集中于法律授权与目标判断——越来越多的架次由越来越少的操作员承担。"},

  // ===== Public service =====
  { id:"postal-sorter", en:"Postal sorter", zh:"邮件分拣员", sector:"public", composite:90,
    sub:[40,80,15,15],
    en_note:"Mail-sorting was automated decades ago; remaining human work is exception-handling.",
    zh_note:"邮件分拣数十年前已自动化；剩余的人工工作是异常处理。"},
  { id:"postal-carrier", en:"Postal carrier", zh:"邮递员", sector:"public", composite:25,
    sub:[15,55,30,60],
    en_note:"Last-mile delivery to individual addresses across all weather is one of the residual robotics-hard problems.",
    zh_note:"风雨无阻向个体地址的末端投递，是机器人未解的残留难题之一。"},
  { id:"clerk-gov", en:"Government clerk", zh:"政府文员", sector:"public", composite:80,
    sub:[80,15,30,30],
    en_note:"Form processing, scheduling, citizen-facing FAQ — pure routine cognitive plus document handling.",
    zh_note:"表格处理、排期、面向公民的常见问答——纯粹的常规认知加文档处理。"},
  { id:"social-worker", en:"Social worker", zh:"社会工作者", sector:"public", composite:18,
    sub:[15,5,55,90],
    en_note:"Casework can be drafted faster; the home visit, the trust-building, the judgement call are deeply human.",
    zh_note:"案件记录可加速起草；家访、建立信任、关键裁量，深植于人。"},
  { id:"firefighter", en:"Firefighter", zh:"消防员", sector:"public", composite:10,
    sub:[5,30,40,90],
    en_note:"Robotic fire response is a research demo; the embodied team in the burning building is human.",
    zh_note:"机器人灭火是研究演示；着火建筑中的具身队伍仍由人组成。"},

  // ===== Creative =====
  { id:"stock-illustrator", en:"Stock-image illustrator", zh:"图库插画师", sector:"creative", composite:90,
    sub:[80,5,40,15],
    en_note:"Generic stock illustration is the product image-models have been competing on since 2022. Already collapsing as a market.",
    zh_note:"自 2022 年起，通用图库插画即是图像模型竞争的产品。市场已在坍缩。"},
  { id:"concept-artist", en:"Concept artist (game/film)", zh:"游戏/影视概念艺术家", sector:"creative", composite:60,
    sub:[40,5,70,40],
    en_note:"Idea-generation is dramatically accelerated; final-quality production art and IP-specific style maintenance still need humans.",
    zh_note:"创意生成大幅加速；最终成品级原画与 IP 风格守护仍需人工。"},
  { id:"fine-artist", en:"Fine artist (gallery)", zh:"画廊艺术家", sector:"creative", composite:18,
    sub:[10,5,80,70],
    en_note:"The art market trades on artist identity, biography, and curated scarcity. AI-only output is its own (smaller) market.",
    zh_note:"艺术市场交易的是艺术家身份、传记、精选稀缺。纯 AI 输出是其自身（较小的）市场。"},
  { id:"graphic-designer", en:"Graphic designer (logos / marketing)", zh:"平面设计师（标志 / 营销）", sector:"creative", composite:72,
    sub:[60,5,55,40],
    en_note:"Templating and rapid logo iteration accelerate hugely. The brand-system level survives; the freelance-marketplace level shrinks.",
    zh_note:"模板化与快速标志迭代大幅加速。品牌系统层留存；自由职业市场层收窄。"},
  { id:"voice-actor-commercial", en:"Voice actor (commercial)", zh:"配音员（商业）", sector:"creative", composite:80,
    sub:[75,5,45,30],
    en_note:"Generic voiceover is now an LLM-API call. Distinctive performance and union work persists.",
    zh_note:"通用配音已是一次 LLM API 调用。独特表演与工会工作留存。"},
  { id:"voice-actor-character", en:"Voice actor (character / animation)", zh:"配音员（动画 / 角色）", sector:"creative", composite:42,
    sub:[35,5,65,55],
    en_note:"Lead character voice acting is bound to recognisable performers. Background voice work is more exposed.",
    zh_note:"主角配音绑定于可辨识的演员。背景配音更暴露。"},
  { id:"music-producer", en:"Music producer", zh:"音乐制作人", sector:"creative", composite:48,
    sub:[40,5,70,55],
    en_note:"Stems, mastering, and demo generation are AI-amplified. Artist relationships and taste-making are not.",
    zh_note:"分轨、母带、demo 生成由 AI 放大。艺人关系与品味塑造不会。"},
  { id:"songwriter", en:"Songwriter", zh:"词曲作者", sector:"creative", composite:50,
    sub:[40,5,75,40],
    en_note:"Top-line and demo generation accelerate; chart-cutting writers continue because the social signal is human.",
    zh_note:"主旋律与 demo 生成加速；上榜词曲作者持续，因社会信号属人。"},
  { id:"photographer-product", en:"Photographer (commercial product)", zh:"摄影师（商品）", sector:"creative", composite:78,
    sub:[60,30,55,25],
    en_note:"Generated product photography handles most catalogue use cases. Lifestyle and complex sets resist.",
    zh_note:"AI 生成商品摄影涵盖多数图录用例。生活方式与复杂场景仍抗替代。"},
  { id:"photographer-event", en:"Photographer (event)", zh:"摄影师（活动）", sector:"creative", composite:38,
    sub:[20,15,50,70],
    en_note:"Wedding and event photography is a relationship business. AI editing accelerates post; capture stays human.",
    zh_note:"婚礼与活动摄影是关系生意。AI 修图加速后期；拍摄阶段仍属人。"},
  { id:"filmmaker", en:"Filmmaker (independent)", zh:"独立电影人", sector:"creative", composite:35,
    sub:[25,10,80,55],
    en_note:"Pre-viz, VFX, and post-production accelerate dramatically; auteur direction and the human ensemble persist.",
    zh_note:"预可视化、视效、后期大幅加速；作者导演与人之合奏留存。"},
  { id:"vfx-artist", en:"VFX artist", zh:"特效师", sector:"creative", composite:65,
    sub:[55,5,65,30],
    en_note:"Rotoscoping, clean-up, and many compositing tasks compress 5-10×. Senior creative-direction layer is what survives.",
    zh_note:"抠像、清理及大量合成工作压缩 5—10 倍。资深创意指导层为留存。"},
  { id:"architect", en:"Architect", zh:"建筑师", sector:"creative", composite:42,
    sub:[35,5,75,55],
    en_note:"Generative-design and code-compliance are accelerated; client management, judgement, and signing on regulatory submissions remain.",
    zh_note:"生成式设计与规范合规加速；客户管理、判断、监管申报签字仍存。"},
  { id:"fashion-designer", en:"Fashion designer", zh:"时装设计师", sector:"creative", composite:35,
    sub:[25,5,75,55],
    en_note:"Mood-boarding and pattern variations accelerate; collection direction and show-pace remain.",
    zh_note:"灵感板与版型变化加速；系列方向与发布节奏留存。"},

  // ===== Science =====
  { id:"lab-tech", en:"Lab technician (routine assays)", zh:"实验室技术员（常规化验）", sector:"science", composite:62,
    sub:[60,40,40,25],
    en_note:"Standardised assays and pipetting have been progressively automated for two decades. AI accelerates protocol drafting on top.",
    zh_note:"标准化化验与移液二十年来逐步自动化。AI 在其上加速方案起草。"},
  { id:"field-biologist", en:"Field biologist", zh:"野外生物学家", sector:"science", composite:22,
    sub:[20,15,75,70],
    en_note:"Embodied observation in unstructured ecosystems. ID is augmented; the rest is fieldwork.",
    zh_note:"于非结构化生态中的具身观察。识别得以增强；其余是田野工作。"},
  { id:"theory-physicist", en:"Theoretical physicist", zh:"理论物理学家", sector:"science", composite:30,
    sub:[20,5,90,40],
    en_note:"Symbolic AI accelerates derivation; breakthrough physical insight remains human-bound for the foreseeable.",
    zh_note:"符号 AI 加速推导；突破性物理洞见在可见未来仍属人。"},
  { id:"drug-discovery", en:"Drug discovery chemist", zh:"药物发现化学家", sector:"science", composite:50,
    sub:[45,5,75,40],
    en_note:"Property prediction and candidate ranking accelerate substantially; bench validation and judgment-of-leads stay.",
    zh_note:"性质预测与候选排序大幅加速；台架验证与候选研判保留。"},

  // ===== Misc public-facing =====
  { id:"real-estate", en:"Real estate agent", zh:"房产经纪人", sector:"finance", composite:50,
    sub:[40,5,55,70],
    en_note:"Listing search and document preparation collapse; relationship-based negotiation persists where it persists.",
    zh_note:"房源搜索与文件准备坍缩；关系型谈判在其留存处留存。"},
  { id:"clergy", en:"Clergy / religious leader", zh:"神职人员", sector:"public", composite:8,
    sub:[5,5,60,90],
    en_note:"Pastoral presence, ritual authority, and community embeddedness are by definition irreplaceable.",
    zh_note:"牧职临在、仪式权威、社群嵌入，按定义不可替代。"},
  { id:"politician", en:"Politician", zh:"政治家", sector:"public", composite:10,
    sub:[5,5,75,90],
    en_note:"Speeches and briefs may be drafted by AI; legitimacy, accountability, and the public mandate are bound to a person.",
    zh_note:"演说与备忘可由 AI 起草；合法性、问责、公共委托，绑定于一个人。"},
  { id:"diplomat", en:"Diplomat", zh:"外交官", sector:"public", composite:18,
    sub:[15,5,75,80],
    en_note:"Document drafting accelerates; back-channel relationships and credibility-of-promise are deeply human.",
    zh_note:"文件起草加速；后渠关系与承诺可信度深植于人。"},
  { id:"sports-coach", en:"Sports coach", zh:"运动教练", sector:"education", composite:18,
    sub:[10,15,55,85],
    en_note:"Video analysis is augmented hugely; the locker-room and the in-the-moment adjustment are bound to a human leader.",
    zh_note:"影像分析得以极大增强；更衣室与临场调整，绑定于人之领袖。"}
];
